### ISSUE TITLE
Stealth of cuff(s) and belt / anklet parts

### ISSUE THREAD

**Issue by users789** [NorthGlenwalker/OpenNC-Cuffs#3]
I have done this while wearing  my main collar.  Upon clicking either the main right cuff or any of the other cuff/anklets/belt.  Choosing  setting/options  and then clicking stealth.  ONLY the right cuff  stealthed, the left cuff /anklets or belt does NOT  stealth also.

**Comment by NorthGlenwalker** [comment]
Ok sorry this is a known short coming at the moment it will be fixed along with the commands feed down from the collar as it is all controlled from the occ_listen/occ_control script set which listens for commands either from the collar or the main cuff and forwards them in the right format to the slave cuffs.

**Comment by NorthGlenwalker** [comment]
this has been fixed in 7.030 beta
